### ISSUE TITLE
[Question] X-wing 2.0

### ISSUE THREAD

**Issue by Starkman9000** [BSData/swxwing#23]
I was speaking on BSData about a repo for x-wing 2.0 and was directed here. I've loved using this repo for X-wing 1.0 and would love to know if there are plans to move to 2.0, or if I should ask about getting an exception due to the major rule changes that came along with second edition?

**Comment by XWingDrLucky** [comment]
First of all, I'm happy to hear that someone has been using the 1.0 repo...  It's been so long since I've gotten any feedback or bug reports that I was beginning to assume nobody outside my immediate group of friends was using it.

I do plan to update the files to 2.0.  It will pretty much require a complete re-write, but that isn't really a bad thing.  I inherited the basic structure of the 1.0 files when I started maintaining them after Wave 3.  If I had realized how big and how cumbersome they would eventually become, I would have done a complete re-write at that point rather than working from Artic Snake's original files.  I had a second opportunity when BattleScribe 2.0 released and I foolishly let that pass.  I don't intend to let this get past me a third time.

I wrote the files for Legion from scratch and they are way better organized and work how I need them to.  I've got a really rough X-Wing 2.0 file (based on the Legion files) that I've been tinkering with, but between being busy at work and what I perceived as a lack of demand, I haven't been particularly motivated to get them done.  I also have to admit, I was holding out hope that maybe FFG's official app would make other squad building options unnecessary, but that obviously hasn't worked out too well.

Ultimately, I just need to get this done.  I've got most of the pieces in place and I'm finally actually getting some free time again, so I will make it happen.  Give me a few days and I'll get something up - after that, it will basically just be data entry.

**Comment by amis92** [comment]
@Starkman9000 , as you've already mentioned in BSData/bsdata#206, you've already got core set converted. Maybe fork the repo and upload those files to share them with @XWingDrLucky and he can decide whether to go with it, or redo that, and work it out between yourselves.

**Comment by r4dian** [comment]
I use this all the time - surprised to learn it doesn't have any analytics to let the developers know.

Anyway, please do 2.0 - it's currently unplayable thanks to it's own shite app being required.

**Comment by XWingDrLucky** [comment]
I'll have it up by the end of the week.

**Comment by r4dian** [comment]
Hero.

**Comment by XWingDrLucky** [comment]
I've got a catalogue together.  It's still got gaps in it (there's so much content in those conversion kits that I'm just in a data entry bottleneck) but it's ready for people to play with and see how it works.  Let me see about getting it posted...

**Comment by Starkman9000** [comment]
Once it's posted I can help with filling in what blanks I can; just unboxed all my X-Wing stuff last night after moving.

**Comment by XWingDrLucky** [comment]
It's up.  The whole thing.  Done.  It may still be a little bit of time before the files populate onto the battlescribedata.appspot.com page, but it's in place.

I'll probably do some final tweaks to the First Edition files to sort of close them out later this week, but they won't go anywhere.  They'll just exist in parallel, even if they don't get any more updates.
